site_name: WIMS-LTI Documentation
site_author: Quentin Coumes
repo_url: https://github.com/PremierLangage/wims-lti-doc/

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Example: activity_creation_example.md
  - Testing: testing.md
  - License: LICENSE.md
  - Github: https://github.com/PremierLangage/wims-lti/

theme: readthedocs
